language: c
sudo: false

cache:
  directories:
  - $HOME/ocaml
  - $HOME/.opam

install: bash -ex .travis-ci.sh prepare
script: bash -ex .travis-ci.sh build

matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.02 OCAML_RELEASE=3 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.03 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.04 OCAML_RELEASE=2 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.05 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.06 OCAML_RELEASE=1 WITH_OPAM=0
    stage: Build
  - os: linux
    env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=0
    stage: Build
    env: OCAML_VERSION=4.04 OCAML_RELEASE=2 WITH_OPAM=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
  - os: linux
    stage: test
    install:
      - opam switch remove -y 4.10.0 || true
      - opam switch create 4.10.0 --empty
      - eval $(opam env)
      - opam repo add ocaml-beta https://github.com/ocaml/ocaml-beta-repository.git
      - opam update
      - opam install ocaml-variants=4.10.0+trunk
    script:
      - make release
  - os: linux
    env: OCAML_VERSION=4.05 OCAML_RELEASE=0 WITH_OPAM=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
  - os: linux
    env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=1
    stage: Test
    addons:
      apt:
        packages:
        - aspcud
  - os: osx
    env: OCAML_VERSION=4.02 OCAML_RELEASE=3 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.03 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.04 OCAML_RELEASE=2 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.05 OCAML_RELEASE=0 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.06 OCAML_RELEASE=1 WITH_OPAM=0
    stage: Build_macOS
  - os: osx
    env: OCAML_VERSION=4.07 OCAML_RELEASE=1 WITH_OPAM=0
    stage: Build_macOS
